### ISSUE TITLE
not working in mac osx 10.9.2

### ISSUE THREAD

**Issue by ali-nuri** [praveenvijayan/Sublime-Text-2-BIDI#15]
Hi
Tnx for the plug ins
It's not working in mac osx,,,
plz help

Thanks

**Comment by imdark** [comment]
Before running it press ctrl+~, run it and give us the error that appears in the console windows.
also possible the error appears on sublime start up so you can press ctrl+~ after sublime has started and add that too.

**Comment by ali-nuri** [comment]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./rtl.py", line 22, in run
  File "./bidi/algorithm.py", line 613, in get_display
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by majebry** [comment]
I have the same error on Linux Ubuntu 14.4. Hope you consider that.

**Comment by imdark** [comment]
Could you give an example of text that throws this? I will try to repreduce this on a linux.

**Comment by majebry** [comment]
Any Arabic text, I've tried this word "عربي".

**Comment by msoutopico** [comment]
Not working for me either.

**Comment by Paveltarno** [comment]
Same here..

**Comment by ahmedgalal007** [comment]
me either
